In [1]:
# =============================================================================
# COMPENDIO DE EJERCICIOS: INDEXACIÓN, FILTRADO Y AGRUPACIÓN EN PANDAS
# =============================================================================

import pandas as pd
import numpy as np

# Semilla para reproducibilidad
np.random.seed(42)

In [2]:
# -----------------------------------------------------------------------------
# EJERCICIO 1: Selección básica con .loc (etiquetas)
# -----------------------------------------------------------------------------
# Dataset de ventas de productos
fechas = pd.date_range('2024-01-01', periods=10, freq='D')
productos = ['A', 'B', 'C', 'D', 'E']
df_ventas = pd.DataFrame({
    'fecha': np.random.choice(fechas, 20),
    'producto': np.random.choice(productos, 20),
    'cantidad': np.random.randint(1, 10, 20),
    'precio': np.round(np.random.uniform(10, 100, 20), 2)
})
df_ventas.set_index('fecha', inplace=True)
df_ventas.sort_index(inplace=True)

print("=== DATASET VENTAS (indexado por fecha) ===")
print(df_ventas.head(10))

=== DATASET VENTAS (indexado por fecha) ===
           producto  cantidad  precio
fecha
2024-01-02        E         8   64.63
2024-01-02        D         1   58.57
2024-01-03        D         7   96.51
2024-01-03        D         4   50.48
2024-01-04        E         7   48.26
2024-01-04        C         5   39.39
2024-01-05        D         3   77.26
2024-01-05        C         9   75.45
2024-01-05        D         9   61.09
2024-01-06        C         2   96.87

In [3]:
# -----------------------------------------------------------------------------
# Tareas con .loc
# -----------------------------------------------------------------------------
# Tarea 1.1: Selecciona todas las filas desde '2024-01-03' hasta '2024-01-05' inclusive.
# Resultado esperado: DataFrame con fechas en ese rango.

# Tarea 1.2: Selecciona las filas con fecha '2024-01-04' y solo las columnas 'producto' y 'cantidad'.
# Resultado esperado: DataFrame con una fila y dos columnas.

# Tarea 1.3: Selecciona todas las filas donde el producto sea 'A' o 'C' y la cantidad sea mayor a 5.
# Resultado esperado: Filas que cumplan ambas condiciones.

# Tarea 1.4: Usando .loc, asigna el valor 99.99 al precio de todas las filas del producto 'B'.
# Resultado esperado: El precio del producto 'B' cambia a 99.99.

In [4]:
# Tarea 1.1: Selecciona todas las filas desde '2024-01-03' hasta '2024-01-05' inclusive.
# Resultado esperado: DataFrame con fechas en ese rango.
df_ventas.loc[(df_ventas.index>="2024-01-03") & (df_ventas.index<="2024-01-05")]

           producto  cantidad  precio
fecha
2024-01-03        D         7   96.51
2024-01-03        D         4   50.48
2024-01-04        E         7   48.26
2024-01-04        C         5   39.39
2024-01-05        D         3   77.26
2024-01-05        C         9   75.45
2024-01-05        D         9   61.09

In [5]:
type(df_ventas.index)

pandas.DatetimeIndex

In [6]:
# Tarea 1.2: Selecciona las filas con fecha '2024-01-04' y solo las columnas 'producto' y 'cantidad'.
# Resultado esperado: DataFrame con una fila y dos columnas.

In [7]:
df_ventas[df_ventas.index=="2024-01-04"][["producto","cantidad"]]

           producto  cantidad
fecha
2024-01-04        E         7
2024-01-04        C         5

In [8]:
# Tarea 1.3: Selecciona todas las filas donde el producto sea 'A' o 'C' y la cantidad sea mayor a 5.
# Resultado esperado: Filas que cumplan ambas condiciones.

In [9]:
df_ventas.loc[((df_ventas["producto"]=="A") | (df_ventas["producto"]=="B")) & (df_ventas['cantidad']>5) ]

           producto  cantidad  precio
fecha
2024-01-07        B         7   12.82
2024-01-07        A         9   45.56

In [10]:
# Tarea 1.4: Usando .loc, asigna el valor 99.99 al precio de todas las filas del producto 'B'.
# Resultado esperado: El precio del producto 'B' cambia a 99.99.

In [11]:
df_ventas.loc[df_ventas['producto']=='B','precio'] = 99.99

In [12]:
df_ventas.loc[df_ventas['producto']=='B']

           producto  cantidad  precio
fecha
2024-01-07        B         7   99.99
2024-01-08        B         2   99.99

In [13]:

# -----------------------------------------------------------------------------
# EJERCICIO 2: Selección con .iloc (posiciones enteras)
# -----------------------------------------------------------------------------
# Dataset de notas de estudiantes
df_notas = pd.DataFrame({
    'estudiante': ['Ana', 'Luis', 'Marta', 'Jorge', 'Sofia', 'Carlos', 'Elena', 'Pedro'],
    'matematicas': np.random.randint(50, 100, 8),
    'ciencias': np.random.randint(40, 100, 8),
    'historia': np.random.randint(55, 100, 8),
    'promedio': [0]*8  # placeholder
})
print("\n=== DATASET NOTAS ===")
print(df_notas)

# -----------------------------------------------------------------------------
# Tareas con .iloc
# -----------------------------------------------------------------------------
# Tarea 2.1: Selecciona las primeras 3 filas y las columnas 'estudiante' y 'matematicas'.
# Resultado esperado: DataFrame con 3 filas y 2 columnas.

# Tarea 2.2: Selecciona las filas en posiciones 2, 4 y 6 (índices 2,4,6) y todas las columnas.
# Resultado esperado: DataFrame con tres filas (Marta, Sofia, Elena).

# Tarea 2.3: Selecciona las últimas 2 filas y las columnas desde 'ciencias' hasta el final.
# Resultado esperado: Filas de Carlos y Elena, columnas ciencias, historia, promedio.

# Tarea 2.4: Usando .iloc, calcula y asigna el promedio de cada estudiante en la columna 'promedio'
# (pista: usa .iloc[:, 1:4] para seleccionar las notas).
# Resultado esperado: La columna 'promedio' llena con la media de las tres asignaturas.

=== DATASET NOTAS ===
  estudiante  matematicas  ciencias  historia  promedio
0        Ana           94        48        71         0
1       Luis           90        63        62         0
2      Marta           78        40        89         0
3      Jorge           64        83        89         0
4      Sofia           94        47        87         0
5     Carlos           50        63        59         0
6      Elena           74        50        96         0
7      Pedro           56        90        93         0

In [14]:
# Tarea 2.1: Selecciona las primeras 3 filas y las columnas 'estudiante' y 'matematicas'.
# Resultado esperado: DataFrame con 3 filas y 2 columnas.

In [15]:
df_notas.iloc[:3, [0,1]]

  estudiante  matematicas
0        Ana           94
1       Luis           90
2      Marta           78

In [16]:
# Tarea 2.2: Selecciona las filas en posiciones 2, 4 y 6 (índices 2,4,6) y todas las columnas.
# Resultado esperado: DataFrame con tres filas (Marta, Sofia, Elena).

In [17]:
df_notas.iloc[[2,4,6]]

  estudiante  matematicas  ciencias  historia  promedio
2      Marta           78        40        89         0
4      Sofia           94        47        87         0
6      Elena           74        50        96         0

In [18]:
# Tarea 2.3: Selecciona las últimas 2 filas y las columnas desde 'ciencias' hasta el final.
# Resultado esperado: Filas de Carlos y Elena, columnas ciencias, historia, promedio.

In [19]:
df_notas.iloc[-2:,2:]

   ciencias  historia  promedio
6        50        96         0
7        90        93         0

In [20]:
# Tarea 2.4: Usando .iloc, calcula y asigna el promedio de cada estudiante en la columna 'promedio'
# (pista: usa .iloc[:, 1:4] para seleccionar las notas).
# Resultado esperado: La columna 'promedio' llena con la media de las tres asignaturas.

In [21]:
df_notas.iloc[:,-1] = df_notas.iloc[:,1:4].mean(axis =1).astype('int64')

In [22]:
df_notas

  estudiante  matematicas  ciencias  historia  promedio
0        Ana           94        48        71        71
1       Luis           90        63        62        71
2      Marta           78        40        89        69
3      Jorge           64        83        89        78
4      Sofia           94        47        87        76
5     Carlos           50        63        59        57
6      Elena           74        50        96        73
7      Pedro           56        90        93        79

In [23]:
# -----------------------------------------------------------------------------
# EJERCICIO 3: Agrupación básica con .groupby y agregación simple
# -----------------------------------------------------------------------------
# Dataset de ventas por categoría y región
df_ventas2 = pd.DataFrame({
    'region': np.random.choice(['Norte', 'Sur', 'Este', 'Oeste'], 30),
    'categoria': np.random.choice(['Electrónica', 'Ropa', 'Hogar'], 30),
    'ventas': np.random.randint(100, 1000, 30),
    'utilidad': np.random.randint(10, 200, 30)
})
print("\n=== DATASET VENTAS POR REGIÓN Y CATEGORÍA ===")
print(df_ventas2.head(10))

# -----------------------------------------------------------------------------
# Tareas con groupby
# -----------------------------------------------------------------------------
# Tarea 3.1: Agrupa por 'region' y calcula la suma total de 'ventas' por región.
# Resultado esperado: Serie o DataFrame con una fila por región y la suma de ventas.

# Tarea 3.2: Agrupa por 'categoria' y calcula el promedio de 'utilidad' por categoría.
# Resultado esperado: Promedio de utilidad para Electrónica, Ropa y Hogar.

# Tarea 3.3: Agrupa por 'region' y 'categoria' y obtén el número de transacciones (count) por grupo.
# Resultado esperado: Tabla con regiones y categorías como índices múltiples y el conteo.

=== DATASET VENTAS POR REGIÓN Y CATEGORÍA ===
  region    categoria  ventas  utilidad
0    Sur        Hogar     781        71
1  Norte        Hogar     656       174
2  Oeste         Ropa     673        60
3   Este        Hogar     745       181
4  Norte        Hogar     895       161
5  Oeste  Electrónica     127        68
6  Oeste        Hogar     719       127
7    Sur        Hogar     655       169
8  Norte         Ropa     439       105
9  Oeste         Ropa     897       189

In [24]:
# Tarea 3.1: Agrupa por 'region' y calcula la suma total de 'ventas' por región.
# Resultado esperado: Serie o DataFrame con una fila por región y la suma de ventas.

In [25]:
print(df_ventas2.groupby(by = "region").sum())

                                                categoria  ventas  utilidad
region
Este    HogarElectrónicaHogarElectrónicaHogarElectróni...    4996      1005
Norte   HogarHogarRopaElectrónicaHogarElectrónicaHogar...    5203      1009
Oeste        RopaElectrónicaHogarRopaHogarRopaElectrónica    3476       784
Sur                         HogarHogarHogarHogarHogarRopa    3731       706

In [26]:
# Tarea 3.2: Agrupa por 'categoria' y calcula el promedio de 'utilidad' por categoría.
# Resultado esperado: Promedio de utilidad para Electrónica, Ropa y Hogar.

In [27]:
print(df_ventas2.groupby(by = ["categoria"])["utilidad"].mean())

categoria
Electrónica    104.875000
Hogar          121.125000
Ropa           121.166667
Name: utilidad, dtype: float64

In [28]:
# Tarea 3.3: Agrupa por 'region' y 'categoria' y obtén el número de transacciones (count) por grupo.
# Resultado esperado: Tabla con regiones y categorías como índices múltiples y el conteo.

In [29]:
print(df_ventas2.groupby(by = ['region','categoria']).count())

                    ventas  utilidad
region categoria
Este   Electrónica       4         4
       Hogar             5         5
Norte  Electrónica       2         2
       Hogar             4         4
       Ropa              2         2
Oeste  Electrónica       2         2
       Hogar             2         2
       Ropa              3         3
Sur    Hogar             5         5
       Ropa              1         1

In [30]:
# -----------------------------------------------------------------------------
# EJERCICIO 4: Agregaciones múltiples con .agg
# -----------------------------------------------------------------------------
# Mismo dataset df_ventas2

# Tarea 4.1: Agrupa por 'region' y aplica .agg para obtener: suma de ventas, promedio de utilidad,
# y desviación estándar de ventas. Renombra las columnas a 'total_ventas', 'utilidad_promedio', 'std_ventas'.
# Resultado esperado: DataFrame con regiones como índice y las tres métricas.

# Tarea 4.2: Agrupa por 'categoria' y aplica funciones personalizadas con .agg:
# - Rango de ventas (max - min)
# - Mediana de utilidad
# Resultado esperado: DataFrame con categorías y las dos nuevas métricas.

# Tarea 4.3: Usa named aggregation para agrupar por 'region' y calcular:
#   ventas_max = max de ventas
#   utilidad_min = min de utilidad
#   ventas_mean = media de ventas
# Resultado esperado: DataFrame con regiones y columnas con esos nombres.

In [31]:
# Tarea 4.1: Agrupa por 'region' y aplica .agg para obtener: suma de ventas, promedio de utilidad,
# y desviación estándar de ventas. Renombra las columnas a 'total_ventas', 'utilidad_promedio', 'std_ventas'.
# Resultado esperado: DataFrame con regiones como índice y las tres métricas.

In [32]:
resultado = df_ventas2.groupby('region').agg(
    total_ventas=('ventas', 'sum'),
    std_ventas=('ventas', 'std'),
    utilidad_promedio=('utilidad', 'mean')
)

print(resultado)

        total_ventas  std_ventas  utilidad_promedio
region
Este            4996  195.347411         111.666667
Norte           5203  161.974370         126.125000
Oeste           3476  274.727657         112.000000
Sur             3731  133.022429         117.666667

In [33]:
# Tarea 4.2: Agrupa por 'categoria' y aplica funciones personalizadas con .agg:
# - Rango de ventas (max - min)
# - Mediana de utilidad
# Resultado esperado: DataFrame con categorías y las dos nuevas métricas.

In [34]:
print( df_ventas2.groupby('categoria').agg(
        rango_ventasMIN = ('ventas','min'),
        rango_ventasMAX = ('ventas','max'),
        mean_utility = ('utilidad','mean')
))

             rango_ventasMIN  rango_ventasMAX  mean_utility
categoria
Electrónica              127              844    104.875000
Hogar                    447              895    121.125000
Ropa                     289              897    121.166667

In [35]:
# Tarea 4.3: Usa named aggregation para agrupar por 'region' y calcular:
#   ventas_max = max de ventas
#   utilidad_min = min de utilidad
#   ventas_mean = media de ventas
# Resultado esperado: DataFrame con regiones y columnas con esos nombres.

In [36]:
print( df_ventas2.groupby('region').agg(
        rango_ventasMAX = ('ventas','max'),
        utilidadMIN = ('utilidad','min'),
        sales_utility = ('ventas','mean')
))

        rango_ventasMAX  utilidadMIN  sales_utility
region
Este                809           48     555.111111
Norte               895           21     650.375000
Oeste               897           60     496.571429
Sur                 781           11     621.833333

In [37]:
# -----------------------------------------------------------------------------
# EJERCICIO 5: Filtrado de grupos con .filter
# -----------------------------------------------------------------------------
# Dataset de empleados
df_empleados = pd.DataFrame({
    'departamento': np.random.choice(['RH', 'IT', 'Ventas', 'Marketing'], 20),
    'salario': np.random.randint(30000, 90000, 20),
    'edad': np.random.randint(22, 60, 20),
    'experiencia': np.random.randint(0, 30, 20)
})
print("\n=== DATASET EMPLEADOS ===")
print(df_empleados)

# -----------------------------------------------------------------------------
# Tareas con .filter
# -----------------------------------------------------------------------------
# Tarea 5.1: Filtra los departamentos cuyo salario promedio sea mayor a 55000.
# Resultado esperado: DataFrame completo solo con filas de los departamentos que cumplen.

# Tarea 5.2: Filtra los departamentos que tengan al menos 5 empleados.
# Resultado esperado: DataFrame con departamentos que cumplen la condición.

# Tarea 5.3: Filtra los departamentos donde la edad máxima sea menor a 50.
# Resultado esperado: DataFrame con departamentos cuya edad máxima < 50.

=== DATASET EMPLEADOS ===
   departamento  salario  edad  experiencia
0        Ventas    82083    40           15
1            IT    70545    47           24
2            IT    30197    24           19
3            RH    53509    40           27
4     Marketing    64698    41           16
5            IT    74542    53            1
6     Marketing    45087    28            0
7            IT    52671    54           15
8     Marketing    55184    39           29
9        Ventas    57848    22           11
10    Marketing    72107    32            4
11       Ventas    50666    49            4
12       Ventas    74357    46           26
13    Marketing    81663    44           22
14       Ventas    45708    52            8
15           RH    56370    51            8
16       Ventas    79811    56            2
17           IT    32811    28           18
18    Marketing    86250    37           15
19           RH    77011    47           15

In [38]:
# Tarea 5.1: Filtra los departamentos cuyo salario promedio sea mayor a 55000.
# Resultado esperado: DataFrame completo solo con filas de los departamentos que cumplen.

In [39]:
df_empleados_top = (
    df_empleados
    .groupby('departamento')
    .filter(lambda x: x['salario'].mean() > 55000) # <--- El .filter va ANTES, sin el .agg()
)

print(df_empleados_top)

   departamento  salario  edad  experiencia
0        Ventas    82083    40           15
3            RH    53509    40           27
4     Marketing    64698    41           16
6     Marketing    45087    28            0
8     Marketing    55184    39           29
9        Ventas    57848    22           11
10    Marketing    72107    32            4
11       Ventas    50666    49            4
12       Ventas    74357    46           26
13    Marketing    81663    44           22
14       Ventas    45708    52            8
15           RH    56370    51            8
16       Ventas    79811    56            2
18    Marketing    86250    37           15
19           RH    77011    47           15

In [40]:
# Tarea 5.2: Filtra los departamentos que tengan al menos 5 empleados.
# Resultado esperado: DataFrame con departamentos que cumplen la condición.

In [41]:
df_empleados_top = df_empleados.groupby('departamento').count()


print(df_empleados_top.loc[(df_empleados_top['edad']>5)].index.values)

<StringArray>
['Marketing', 'Ventas']
Length: 2, dtype: str

In [42]:
# Tarea 5.3: Filtra los departamentos donde la edad máxima sea menor a 50.
# Resultado esperado: DataFrame con departamentos cuya edad máxima < 50.

In [43]:
print(df_empleados.loc[(df_empleados['edad']<50)])

   departamento  salario  edad  experiencia
0        Ventas    82083    40           15
1            IT    70545    47           24
2            IT    30197    24           19
3            RH    53509    40           27
4     Marketing    64698    41           16
6     Marketing    45087    28            0
8     Marketing    55184    39           29
9        Ventas    57848    22           11
10    Marketing    72107    32            4
11       Ventas    50666    49            4
12       Ventas    74357    46           26
13    Marketing    81663    44           22
17           IT    32811    28           18
18    Marketing    86250    37           15
19           RH    77011    47           15

In [44]:
# -----------------------------------------------------------------------------
# EJERCICIO 6: Combinación de .loc con condiciones de grupo
# -----------------------------------------------------------------------------
# Mismo dataset df_empleados

# Tarea 6.1: Calcula el salario promedio por departamento y luego, usando .loc,
# selecciona los empleados cuyo salario sea superior al promedio de su propio departamento.
# Resultado esperado: Filas de empleados con salario > media departamental.

# Pista: puedes usar groupby + transform('mean') para crear una columna auxiliar.

# Tarea 6.2: Similar al anterior, pero selecciona únicamente los empleados del departamento 'IT'
# cuya experiencia supere la mediana de experiencia de todo el departamento 'IT'.
# Resultado esperado: Empleados de IT con experiencia > mediana de IT.

In [45]:
# Tarea 6.1: Calcula el salario promedio por departamento y luego, usando .loc,
# selecciona los empleados cuyo salario sea superior al promedio de su propio departamento.
# Resultado esperado: Filas de empleados con salario > media departamental.

In [46]:
e61 = df_empleados.groupby('departamento')['salario'].transform('mean')
e61

0     65078.833333
1     52153.200000
2     52153.200000
3     62296.666667
4     67498.166667
5     52153.200000
6     67498.166667
7     52153.200000
8     67498.166667
9     65078.833333
10    67498.166667
11    65078.833333
12    65078.833333
13    67498.166667
14    65078.833333
15    62296.666667
16    65078.833333
17    52153.200000
18    67498.166667
19    62296.666667
Name: salario, dtype: float64

In [47]:
highPaidEmployees = df_empleados.loc[df_empleados['salario']>e61]

highPaidEmployees

   departamento  salario  edad  experiencia
0        Ventas    82083    40           15
1            IT    70545    47           24
5            IT    74542    53            1
7            IT    52671    54           15
10    Marketing    72107    32            4
12       Ventas    74357    46           26
13    Marketing    81663    44           22
16       Ventas    79811    56            2
18    Marketing    86250    37           15
19           RH    77011    47           15

In [48]:
e62 = df_empleados.groupby('departamento')['salario'].mean()
e62

departamento
IT           52153.200000
Marketing    67498.166667
RH           62296.666667
Ventas       65078.833333
Name: salario, dtype: float64

In [49]:
# Tarea 6.2: Similar al anterior, pero selecciona únicamente los empleados del departamento 'IT'
# cuya experiencia supere la mediana de experiencia de todo el departamento 'IT'.
# Resultado esperado: Empleados de IT con experiencia > mediana de IT.

In [50]:
df_IT = df_empleados.loc[df_empleados['departamento']=='IT']

In [51]:
df_IT

   departamento  salario  edad  experiencia
1            IT    70545    47           24
2            IT    30197    24           19
5            IT    74542    53            1
7            IT    52671    54           15
17           IT    32811    28           18

In [52]:
expIT = df_IT.groupby('departamento')['experiencia'].transform('mean')
expIT

1     15.4
2     15.4
5     15.4
7     15.4
17    15.4
Name: experiencia, dtype: float64

In [53]:
highExpEmployees = df_IT.loc[df_IT['experiencia']>expIT]

In [54]:
highExpEmployees

   departamento  salario  edad  experiencia
1            IT    70545    47           24
2            IT    30197    24           19
17           IT    32811    28           18

In [55]:
# -----------------------------------------------------------------------------
# EJERCICIO 7: Indexación avanzada con fechas y .loc
# -----------------------------------------------------------------------------
# Dataset de series temporales
fechas_h = pd.date_range('2024-01-01', periods=100, freq='h')
df_temp = pd.DataFrame({
    'temperatura': np.random.normal(20, 5, 100),
    'humedad': np.random.randint(30, 90, 100)
}, index=fechas_h)
print("\n=== DATASET TEMPERATURA (cada hora) ===")
print(df_temp.head())

# -----------------------------------------------------------------------------
# Tareas con fechas
# -----------------------------------------------------------------------------
# Tarea 7.1: Selecciona todas las mediciones entre '2024-01-02 06:00:00' y '2024-01-03 18:00:00'.
# Resultado esperado: DataFrame con ese rango de horas.

# Tarea 7.2: Selecciona las filas correspondientes al día 2024-01-03 (completo).
# Resultado esperado: 24 filas (cada hora del día).

# Tarea 7.3: Usando .loc, cambia el valor de humedad a 99 para todas las filas donde la temperatura
# sea mayor a 25 grados.
# Resultado esperado: La humedad en esas filas pasa a 99.

=== DATASET TEMPERATURA (cada hora) ===
                     temperatura  humedad
2024-01-01 00:00:00    23.088204       51
2024-01-01 01:00:00    26.085354       58
2024-01-01 02:00:00    21.131441       84
2024-01-01 03:00:00    24.237007       32
2024-01-01 04:00:00    20.874165       41

In [ ]:
# Tarea 7.1: Selecciona todas las mediciones entre '2024-01-02 06:00:00' y '2024-01-03 18:00:00'.
# Resultado esperado: DataFrame con ese rango de horas.

In [58]:
df_temp.loc[(df_temp.index>'2024-01-02 06:00:00') & (df_temp.index<'2024-01-03 18:00:00')]

                     temperatura  humedad
2024-01-02 07:00:00    19.313641       66
2024-01-02 08:00:00    19.379338       52
2024-01-02 09:00:00    23.701704       87
2024-01-02 10:00:00    17.737689       39
2024-01-02 11:00:00    23.885249       83
2024-01-02 12:00:00    25.227856       34
2024-01-02 13:00:00    18.289291       65
2024-01-02 14:00:00    15.369767       63
2024-01-02 15:00:00    17.435173       81
2024-01-02 16:00:00    23.550546       60
2024-01-02 17:00:00    20.462394       39
2024-01-02 18:00:00    23.150375       87
2024-01-02 19:00:00    28.814687       48
2024-01-02 20:00:00    21.154769       87
2024-01-02 21:00:00    15.955316       61
2024-01-02 22:00:00    25.287118       30
2024-01-02 23:00:00    20.256804       85
2024-01-03 00:00:00    24.362236       34
2024-01-03 01:00:00    25.330993       74
2024-01-03 02:00:00    15.204960       33
2024-01-03 03:00:00    26.910023       45
2024-01-03 04:00:00    24.525610       53
2024-01-03 05:00:00    16.980478       45
2024-01-03 06:00:00    21.522246       84
2024-01-03 07:00:00    21.286037       31
2024-01-03 08:00:00    20.119659       78
2024-01-03 09:00:00    24.359570       57
2024-01-03 10:00:00    27.186782       61
2024-01-03 11:00:00    20.036532       56
2024-01-03 12:00:00    26.654407       49
2024-01-03 13:00:00    24.941013       53
2024-01-03 14:00:00    21.161481       41
2024-01-03 15:00:00    20.880905       79
2024-01-03 16:00:00    14.237173       64
2024-01-03 17:00:00    12.496158       89

In [ ]:
# Tarea 7.2: Selecciona las filas correspondientes al día 2024-01-03 (completo).
# Resultado esperado: 24 filas (cada hora del día).

In [64]:
df_temp.loc['2024-01-03']

                     temperatura  humedad
2024-01-03 00:00:00    24.362236       34
2024-01-03 01:00:00    25.330993       74
2024-01-03 02:00:00    15.204960       33
2024-01-03 03:00:00    26.910023       45
2024-01-03 04:00:00    24.525610       53
2024-01-03 05:00:00    16.980478       45
2024-01-03 06:00:00    21.522246       84
2024-01-03 07:00:00    21.286037       31
2024-01-03 08:00:00    20.119659       78
2024-01-03 09:00:00    24.359570       57
2024-01-03 10:00:00    27.186782       61
2024-01-03 11:00:00    20.036532       56
2024-01-03 12:00:00    26.654407       49
2024-01-03 13:00:00    24.941013       53
2024-01-03 14:00:00    21.161481       41
2024-01-03 15:00:00    20.880905       79
2024-01-03 16:00:00    14.237173       64
2024-01-03 17:00:00    12.496158       89
2024-01-03 18:00:00    20.825114       62
2024-01-03 19:00:00    15.720355       62
2024-01-03 20:00:00    19.801819       80
2024-01-03 21:00:00    17.326686       72
2024-01-03 22:00:00    11.057517       66
2024-01-03 23:00:00    21.786523       41

In [ ]:
# Tarea 7.3: Usando .loc, cambia el valor de humedad a 99 para todas las filas donde la temperatura
# sea mayor a 25 grados.
# Resultado esperado: La humedad en esas filas pasa a 99.

In [66]:
df_temp.loc[df_temp['temperatura']>25.0, 'humedad'] = 99

In [69]:
df_temp.loc[df_temp['temperatura']>25, ['humedad','temperatura']]

                     humedad  temperatura
2024-01-01 01:00:00       99    26.085354
2024-01-01 06:00:00       99    25.246737
2024-01-01 07:00:00       99    26.625528
2024-01-01 13:00:00       99    26.341948
2024-01-01 22:00:00       99    26.046910
2024-01-02 00:00:00       99    33.672111
2024-01-02 12:00:00       99    25.227856
2024-01-02 19:00:00       99    28.814687
2024-01-02 22:00:00       99    25.287118
2024-01-03 01:00:00       99    25.330993
2024-01-03 03:00:00       99    26.910023
2024-01-03 10:00:00       99    27.186782
2024-01-03 12:00:00       99    26.654407
2024-01-04 04:00:00       99    27.801901
2024-01-04 08:00:00       99    31.945180
2024-01-04 09:00:00       99    29.217069
2024-01-04 10:00:00       99    26.817177
2024-01-04 14:00:00       99    25.240099
2024-01-04 19:00:00       99    28.306509
2024-01-05 01:00:00       99    26.332034
2024-01-05 03:00:00       99    28.256755