**Pruebas para aprender el sistema de la API de pandas para manipular datos en DataScience**

**Función	Descripción	Ejemplo de uso:**
sum	Suma	                            .groupby(...).sum()
mean	Promedio	                    .groupby(...).mean()
median	Mediana                         .groupby(...).median()
min	Valor mínimo	                    .groupby(...).min()
max	Valor máximo	                    .groupby(...).max()
count	Cuenta no nulos	                .groupby(...).count()
size	Cuenta total (incluye nulos)	.groupby(...).size()
std	Desviación estándar	                .groupby(...).std()
var	Varianza	                        .groupby(...).var()
first	Primer valor del grupo	        .groupby(...).first()
last	Último valor del grupo	        .groupby(...).last()
nunique	Número de valores únicos	    .groupby(...).nunique()
prod	Producto de los valores	        .groupby(...).prod()
sem	Error estándar de la media	        .groupby(...).sem()
mad	Desviación absoluta de la mediana	.groupby(...).mad() (menos común)

Ejemplo1:

In [1]:
import pandas as pd

data = {
    "producto": ["A", "A", "B", "B", "C", "C"],
    "categoria": ["x", "x", "y", "y", "z", "z"],
    "cantidad": [10, 20, 15, 5, 8, 12],
    "precio_unitario": [100, 100, 200, 200, 150, 150]
}

ventas = pd.DataFrame(data)
ventas["total"] = ventas["cantidad"] * ventas["precio_unitario"]
print(ventas)

  producto categoria  cantidad  precio_unitario  total
0        A         x        10              100   1000
1        A         x        20              100   2000
2        B         y        15              200   3000
3        B         y         5              200   1000
4        C         z         8              150   1200
5        C         z        12              150   1800

 **1. Suma total por producto**

In [2]:
print(ventas.groupby("producto")["total"].sum()
)

producto
A    3000
B    4000
C    3000
Name: total, dtype: int64

 **2. Media de cantidad por categoría**

In [3]:
print(ventas.groupby("categoria")["cantidad"].mean())

categoria
x    15.0
y    10.0
z    10.0
Name: cantidad, dtype: float64

**3. Agregaciones múltiples**

In [4]:
df1=ventas.groupby("producto").agg({
    "cantidad": "sum",
    "total": ["mean", "sum"]
})

# Aplanar columnas OJOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO APLANAS COLUMNAS CUANDO HAGO múltiples agregaciones
df1.columns = ['_'.join(col) for col in df1.columns]
df1 = df1.reset_index()
print(df1)

  producto  cantidad_sum  total_mean  total_sum
0        A            30      1500.0       3000
1        B            20      2000.0       4000
2        C            20      1500.0       3000

**4. Agrupaciones por múltiples columnas**

In [5]:
print(ventas.groupby(["categoria", "producto"])["total"].median())

categoria  producto
x          A           1500.0
y          B           2000.0
z          C           1500.0
Name: total, dtype: float64

Ejercicios:
🧩 Ejercicio 1: Total vendido por producto
Con el DataFrame ventas anterior, calcula el total de dinero vendido por cada producto.

🧩 Ejercicio 2: Cantidad total por categoría
Agrupa por categoria y muestra la suma de cantidad para cada una.

🧩 Ejercicio 3: Venta promedio y total por producto
Para cada producto, calcula:

La media (mean) de la columna total
La suma (sum) de la columna cantidad

🧩 Ejercicio 4: Venta total por categoría y producto
Agrupa por categoria y producto, y muestra la venta total (total) de cada combinación.

🧩 Ejercicio 5 (intermedio): Producto más vendido por categoría
Agrupa por categoria y producto, y suma cantidad.

Para cada categoría, encuentra el producto con mayor cantidad vendida.
💡 Pista: usa .groupby() y luego .nlargest(1) dentro de cada grupo.

🧠 Tip extra: Ordenar el resultado
Puedes ordenar un groupby usando sort_values():

ventas.groupby("producto")["total"].sum().sort_values(ascending=False)

Ejercicio 1

In [6]:
print(ventas.groupby(["producto"])["total"].sum())

producto
A    3000
B    4000
C    3000
Name: total, dtype: int64

Ejercicio 2

In [7]:
print(ventas.groupby(["categoria"])["cantidad"].sum())

categoria
x    30
y    20
z    20
Name: cantidad, dtype: int64

Ejercicio 3

In [8]:
print(ventas.groupby(["producto"]).agg({"cantidad":["mean","sum"]}))

         cantidad
             mean sum
producto
A            15.0  30
B            10.0  20
C            10.0  20

In [15]:
import pandas as pd
import dataframe_image as dfi

# 1. Creamos un dataset de ejemplo
data = {
    'Producto': ['Laptop', 'Keyboard', 'Monitor', 'Gamepad', 'Speakers', 'Printer', 'WebCam', 'USB Hub'],
    'Categoría': ['Electrónica', 'Periférico', 'Electrónica', 'Periférico', 'Periférico', 'Otro', 'Electrónica', 'Otro']
}

df = pd.DataFrame(data)

print("--- Tabla Original ---")
display(df)
dfi.export(df, 'tabla_Noencoding.png', table_conversion='matplotlib')
# 2. Aplicamos One-Hot Encoding usando pandas
# El parámetro 'dtype=int' es para que nos dé 0 y 1 en lugar de True/False
df_encoded = pd.get_dummies(df, columns=['Categoría'], prefix='Es', dtype=int, drop_first=True)

print("\n--- Tabla con One-Hot Encoding ---")
display(df_encoded)

dfi.export(df_encoded, 'tabla_resultado.png', table_conversion='matplotlib')

--- Tabla Original ---

   Producto    Categoría
0    Laptop  Electrónica
1  Keyboard   Periférico
2   Monitor  Electrónica
3   Gamepad   Periférico
4  Speakers   Periférico
5   Printer         Otro
6    WebCam  Electrónica
7   USB Hub         Otro

--- Tabla con One-Hot Encoding ---

   Producto  Es_Otro  Es_Periférico
0    Laptop        0              0
1  Keyboard        0              1
2   Monitor        0              0
3   Gamepad        0              1
4  Speakers        0              1
5   Printer        1              0
6    WebCam        0              0
7   USB Hub        1              0